### ISSUE TITLE
CS0012: The type 'System.Web.Mvc.MvcHtmlString' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by antukidem** [VannaDii/OneAll#2]
Project build successfully, but would through this exception when i  click on login link from the main window

**Comment by VannaDii** [comment]
If the project builds then the proper assemblies are available at build time, if it does not run then this is an issue with the environment in which you're attempting to run it. You should verify that the assemblies required to build are deployed to the environment on which you intend to run. If you're running in IIS, make sure that the target framework version (.Net v2 or v4) matches for whichever you've compiled against.

This issue will be marked as "wontfix" since it's a deployment issue and not a project issue.

**Comment by antukidem** [comment]
see original error:

Compilation Error
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.

Compiler Error Message: CS0012: The type 'System.Web.Mvc.MvcHtmlString' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

Source Error:

Line 1:  <%@ Page Title="Log In" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeBehind="Login.aspx.cs" Inherits="OneAll.ASPNET.Account.Login" %>
Line 2:  <asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
Line 3:      <%= Page.OneAllHeaderScript() %>
Line 4:  /asp:Content
Line 5:  <asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">

Source File: c:\Users\Administrator\Downloads\OneAll-master\OneAll-master\Demo\Account\Login.aspx    Line: 3

**Comment by VannaDii** [comment]
Based on this message, you’re trying to use the MVC library in an ASPX (non-MVC) site. There are three different CSPROJ (Projects), each one results in a library for a different scenario. If you’re going to use the library in an ASPX (non-MVC) site then you need to use the non-MVC library (OneAll.ASPNET.csproj) and still be mindful of matching .Net  Framework versions.

**Comment by antukidem** [comment]
following the instruction above, this is what I get

[OneAll Social Login] To enforce the security of our services we require each domain to be whitelisted. Please click here to open your security settings and whitelist the domain localhost. Reload this page afterwards.

I have removed the MVC class project since i am using asp.net
I have added my domain . and i have also added local host since I am testing off my local box. but still get the error

**Comment by VannaDii** [comment]
You'll need to contact OneAll directly as that us a response from their server. If you've got an undesirable response from their server you'll need to seek their support.

Sent from a mobile device

**Comment by antukidem** [comment]
it is working now.

Many thanks
