### ISSUE TITLE
Can not pull twitter users email

### ISSUE THREAD

**Issue by antukidem** [VannaDii/OneAll#3]
using OneAll API, I cannot retrieve email from identity object for users who log in with twitter account.

Email field is always null.

please help

**Comment by VannaDii** [comment]
Again, I have to stress that this is not OneAll support forum. If the SDK is preventing you from interacting with the service then please provide the error.

You will never get an email from a twitter user, twitter will not provide that.

-derik

Sent from a mobile device

**Comment by antukidem** [comment]
Please what is their support forum url?
