### ISSUE TITLE
OneAll API sample for ASP.NET MVC2

### ISSUE THREAD

**Issue by anshuman21** [VannaDii/OneAll#5]
Hi,
We currently have a ASP.NET MVC2 Web project in our solution. I have written the following code in the ViewPage <%= this.Page.OneAllDisplayLogOnScript() %>. I' m getting the following error : 'System.Web.UI.Page' does not contain a definition for 'OneAllDisplayLogOnScript' and no extension method 'OneAllDisplayLogOnScript' accepting a first argument of type 'System.Web.UI.Page' could be found (are you missing a using directive or an assembly reference?)

Can you please suggest a solution for this ?

**Comment by VannaDii** [comment]
Please use other established forums for general programming issues. Try stackoverflow.com or search your error. http://www.bing.com/search?q=System.Web.UI.Page+does+not+contain+a+definition+for+and+no+extension+method+accepting+a+first+argument+of+type+System.Web.UI.Page+could+be+found+are+you+missing+a+using+directive+or+an+assembly+reference

**Comment by anshuman21** [comment]
Can you provide me the code to call the 'OneAllDisplayLogOnScript' in a ASP.NET MVC2 Web project ?

**Comment by VannaDii** [comment]
The SDK is the code that's provided for OneAll. Your implementation code is up to you.

**Comment by anshuman21** [comment]
The SDK has code which provides implementation for a ASP.NET Webforms project. Can you please provide me the sample code for a calling the 'OneAllDisplayLogOnScript' method in a ASP.NET MVC2 ViewPage ?

**Comment by VannaDii** [comment]
The SDK also include a sample of calling it in MVC. Regardless of your Visual Studio project template, a .Net method is still a .Net method and can be called from anything that supports running .Net. I cannot provide you with implementation code. There's no charge for the SDK (which took several months to write and test) expecting someone to write your implementation code for you for free is a bit disrespectful IMO. I hope you have success in your project and if the OneAll SDK is useful then that's fantastic, if not then I hope you find what works for you.
