### ISSUE TITLE
oneAllUser.Identities.Identity is always null

### ISSUE THREAD

**Issue by K232** [VannaDii/OneAll#7]
Hi Derik,
in Line 42 of Social.aspx.cs, oneAllUser.Identities.Identity is always null for me :-( Any idea why and how to fix it?
Thanks!
P.S. I'm using the Facebook Login

**Comment by VannaDii** [comment]
That object is directly deserialized from the OneAll response, so it's most likely the OneAll response either no longer contains an "identities" field or possibly the name has been changed.

This could easily be determined by running Fiddler or Charles while executing this demo code and observing the OneAll response and adjusting the DataMember attribute values to reflect the data being sent.

**Comment by K232** [comment]
So everyone using the OneAll .net SDK will have the problem now? Did someone else (or you, Derik) already run into the same problem? I'm still hoping I just made a mistake somewhere but I just replaced the keys in the web.config of your demo app and it runs fine until line 42.
Are there any plans for further investigations from your side, Derik? Thanks!

**Comment by VannaDii** [comment]
This was a pretty simple thing to fix. Feel free to make bug fixes or other useful contributions to this project, especially if you're using it. After all, I didn't open source it just because I wanted to use git.
